version: "3.7"

services:
  db:
    container_name: django_db
    image: postgres:11.2
    volumes:
      - django_data_volume:/var/lib/postgresql/data
  rest_api:
    container_name: django_rest_api
    build:
      context: .
      dockerfile: DockerfilePython
    volumes:
      - ./code/django_rest_api:/code
    tty: true
    expose:
      - "3031"
    depends_on:
      - db
  nginx:
    restart: always
    image: nginx
    depends_on:
      - rest_api
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
  web_front:
    container_name: django_web_front
    build:
      context: .
      dockerfile: DockerfileNode
    volumes:
      - ./code/django_web_front:/code
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - nginx
volumes:
  django_data_volume: